# Generated by Django 3.2.13 on 2022-06-30 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('name',)},
        ),
    ]
